### ISSUE TITLE
Add search command

### ISSUE THREAD

**Issue by fractaledmind** [nalgeon/sqlpkg-cli#15]
Currently, it is impossible to find available packages from the CLI. You have to navigate to the web UI at https://sqlpkg.org and search/explore there. Then, it is difficult to copy the package identifier, as the identifier is a link to the GitHub repo. All in all, package discovery could be improved.

Adding a `sqlpkg search {phrase}` command would allow users of the CLI to search the registry's packages exactly like via the searchbar on the https://sqlpkg.org page, making it easier to discover packages available to install.

**Comment by nalgeon** [comment]
Yeah, I don't know about that.

I totally agree that a CLI-based search would be nice. At the same time, I'm pretty happy with the basic feature set right now.

And Python or Go do just fine without CLI search or registry (#14). So I think I'll pass for now.

**Comment by fractaledmind** [comment]
Your choice. Thanks for the great lib
