### ISSUE TITLE
install error "invalid cross-device link"

### ISSUE THREAD

**Issue by atomotic** [nalgeon/sqlpkg-cli#17]
error occurs when home directory is in a different partition than /tmp

```
sqlpkg install sqlite/zipfile
(project scope)
> installing sqlite/zipfile...
! failed to copy downloaded files: rename /tmp/.sqlpkg/sqlite/zipfile .sqlpkg/sqlite/zipfile: invalid cross-device link
```
something different than [os.Rename](https://github.com/nalgeon/sqlpkg-cli/blob/main/fileio/fileio.go#L49) should be used, as [example](https://gist.github.com/var23rav/23ae5d0d4d830aff886c3c970b8f6c6b?permalink_comment_id=4431960#gistcomment-4431960)

**Comment by nalgeon** [comment]
Fixed in [0.2.3](https://github.com/nalgeon/sqlpkg-cli/releases/0.2.3).
