### ISSUE TITLE
How to install new executables for existing packages in project-scope in CI

### ISSUE THREAD

**Issue by fractaledmind** [nalgeon/sqlpkg-cli#18]
Trying to install all packages as a part of the CI process isn't working:
```
Run bundle exec sqlpkg install
(project scope)
> installing https://github.com/nalgeon/sqlpkg/raw/main/pkg/asg017/ulid.json...
✓ already at the v0.2.1 version
installed 1 packages

Run bin/rails db:setup test test:system
.sqlpkg/asg017/ulid/ulid0.dylib.so: cannot open shared object file: No such file or directory
```
It _seems_ that `sqlpkg install` sees that there is already one executable binary and halting, even though that binary is not the binary for the host operating system.

**Comment by nalgeon** [comment]
I'm sorry to reiterate on this, but this is essentially the same issue as #16.

It's not working because you committed the `.sqlpkg` directory. This directory is not meant to be committed. It's like `node_modules` in JS (not sure what the analog is in the Ruby world).

**Comment by fractaledmind** [comment]
So if we only commit the lockfile, things should work?

**Comment by fractaledmind** [comment]
Ok, tested and that works. Projects need to only commit the lockfile and run the installation as a part of CI and deployment. I will update the gem and the docs.
