### ISSUE TITLE
Installing an extension on linux needs a few extra steps

### ISSUE THREAD

**Issue by bobhy** [nalgeon/sqlpkg-cli#19]
Following the instructions for installing an extension on linux, I kept running into 'file not found' errors trying to load the extension, even after double checking the path in `.load` or `select load_extension()`., adding execute permission to the files, etc.  

I eventually got things working by registering the extensions properly with the linux dynamic linker, `ldconfig`.  

I'd like to see the install doc updated to describe this (or a simplified version, if someone can suggest one), or have `sqlpkg` enhanced to just do it.  

Here's what worked for me:

1. Choose the local directory into which you're going to download all your extension '*.so' files.  e.g `~/lib`.  
1. Update `/etc/ld.so.conf.d` to refer to the above directory.  
0. Download your chosen extension(s) to above directory.
1. Rename each file to match glob `lib*.so*`. e.g `mv regex0.so libregex0.so`
2. run `$ sudo ldconfig`.  This updates a system wide cache of shared libraries and discovers your extensions.
3. Configure `sqlite` to load the extension.  e.g `.load libregex0` will now work, no need to specify absolute path or the `.so` extension.

 I would take a crack at a PR for a fix,  if invited.

**Comment by nalgeon** [comment]
Sorry, I prefer to use an explicit path to load an extension. The steps in the docs work for me. If you provide specific steps to reproduce the problem, I'll look into it.

**Comment by bobhy** [comment]
I cannot reproduce my original failure any longer, and, as you say, the documented steps do work.    
This issue should be closed with status 'not reproducible', and sorry for the confusion!

**Comment by nalgeon** [comment]
No worries :) Thanks for trying sqlpkg!
