### ISSUE TITLE
Respect XDG Base Directories

### ISSUE THREAD

**Issue by jamie** [nalgeon/sqlpkg-cli#3]
For Linux/MacOS, in the global scope can we respect the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) rather than hard-coding against $HOME?

I would expect this would just be an extra check in cmd.go `inferWorkDir`, checking for the appropriate environment variable and using that instead of $HOME if present.

In the context of ~/.sqlpkg, I believe the correct standard path would be `$XDG_DATA_HOME/sqlpkg` without the dot, but if it helps consistency with other code (specifically this looks like it would cause some extra work around `spec.DirName`)  then `$XDG_DATA_HOME/.sqlpkg` is acceptable.

**Comment by nalgeon** [comment]
Sorry, I'm going to pass on this.
