### ISSUE TITLE
Adding a WEBI installer

### ISSUE THREAD

**Issue by fractaledmind** [nalgeon/sqlpkg-cli#4]
This is such a great project. I am personally pushing to make working with SQLite as easy and straight-forward as possible for Rails developers, and I think that this utility fits perfectly into that vision. At present, however, it is cumbersome and manual to install the CLI for projects to then simply and automatically install extensions. In order to hopefully solve this problem and make it similarly simply and automatic to install this utility (across OSes and architectures), I created a WEBI installer: https://github.com/webinstall/webi-installers/pull/651

This is the https://webinstall.dev project, which is a community project to provide easy-to-use installers for cross-platform tools. Hopefully my PR will be merged soon, and then I can open a PR here to add the WEBI installation instructions, which will make this project incredibly simple to get setup across platforms.

**Comment by coolaj86** [comment]
I've finally had a day to go through the Webi PRs and I've got this up on beta for now:
https://beta.webinstall.dev/sqlpkg

My plan is to take a closer look tomorrow morning and bring it .

**Comment by fractaledmind** [comment]
@coolaj86 This is awesome to hear! Thanks for your great work on such a useful and needed project.

**Comment by nalgeon** [comment]
Thanks both of you folks! I'm super excited to see sqlpkg added to webinstall.
