### ISSUE TITLE
`sqlpkg <manage-cmd>` should allow the same URI types as `sqlpkg install`

### ISSUE THREAD

**Issue by coolaj86** [nalgeon/sqlpkg-cli#5]
I would expect that `sqlpkg list` should be able to read the spec file metadata from any source, the same as `sqlpkg install`:

```sh
sqlpkg list <author/pkg>
sqlpkg install <author/pkg>
```

```sh
sqlpkg list <git-uri>
sqlpkg install <git-uri>
```

```sh
sqlpkg list <https-url>
sqlpkg install <https-url>
```

**Comment by coolaj86** [comment]
This didn't work in my testing, but since the example `sqlpkg.json` files referenced in the documentation don't exist and the example commands fail, it may just be that the `sqlpkg info` command fails because the package really doesn't exist. 🤷‍♂️

**Comment by coolaj86** [comment]
@hacdan was able to help confirm that it does work as hoped:

```sh
sqlpkg info https://raw.githubusercontent.com/riyaz-ali/dns.sql/main/sqlpkg.json
```

```text
riyaz-ali/dns.sql@0.1.2 by Riyaz Ali
A sqlite3 extension that allows you to query DNS using SQL
https://github.com/riyaz-ali/dns.sql
license: MIT
✘ not installed
```

**Comment by coolaj86** [comment]
Re-opening because this doesn't work:

```sh
sqlpkg uninstall https://raw.githubusercontent.com/riyaz-ali/dns.sql/main/sqlpkg.json
```

It should be able to read from the spec file and uninstall the local version.

**Comment by nalgeon** [comment]
> I would expect that sqlpkg list should be able to read the spec file metadata from any source

`list` does not accept arguments. I'd rather not change this.

> It should be able to read from the spec file and uninstall the local version.

`uninstall` only works with the owner/name format. I'd rather not change this.
