### ISSUE TITLE
Follow POSIX and Go standards for `version` and `help`

### ISSUE THREAD

**Issue by coolaj86** [nalgeon/sqlpkg-cli#6]
Just to keep expectations for old dinosaurs like myself:

```
-V, --version, version
```

```
--help, help
```

**Comment by nalgeon** [comment]
Currently there is a clear separation between flags and commands. I'd rather not change that.

**Comment by coolaj86** [comment]
Presently neither `-V` nor `--version` show the version and `--help` does NOT print the help message.

Supporting the standard doesn't require rearchitecting the subcommand structure, it can be done like this:

```go
	if len(os.Args) > 1 {
		if ("version" == strings.TrimLeft(os.Args[1], "-") || "-V" == os.Args[1]) {
			printVersion()
			os.Exit(0)
			return
		}
	}
```
