### ISSUE TITLE
Search with `sqlpkg list` or `sqlpkg info`?

### ISSUE THREAD

**Issue by coolaj86** [nalgeon/sqlpkg-cli#8]
I would imagine that the number of extensions will probably remain below 10,000 for the foreseeable future.

What do you think about making `sqlpkg list` cache the list of packages (and get timestamp-based updates at each run) to be able to view and search (or grep) registered packages?

```sh
sqlpkg list --search stat
```

```text
dessus/stats2  by Keith Medcalf
Even more math statistics functions.

nalgeon/stats  by Richard Hipp
Mathematical statistics.

shawnw/stats3  by Shawn Wagner
Even more math statistics functions.
```

**Comment by nalgeon** [comment]
I'd rather not add any new features right now.
