### ISSUE TITLE
Move `.sqlpkg` to `~/.config/sqlpkg/extensions`

### ISSUE THREAD

**Issue by coolaj86** [nalgeon/sqlpkg-cli#9]
I believe the standard location for extensions would be `~/.config/sqlpkg/extensions` (where "extensions" is an arbitrary name) or `~/.local/share/sqlpkg/lib` (since these are dynamic-loading library files).

I'd lean toward `.config` since when I see `~/.local/share` used it's typically for very dynamic files, such as log files or actual data, or completely static data like man pages, etc. `~/.config` is used by `fish` for dynamically-loaded extensions.

I also think that `<BINDIR>/../lib` would be appropriate, such as `~/.local/opt/sqlpkg/bin/../lib` -  but not `~/.local/bin/../lib` (since these libraries are specific to sqlite and not generally useful).

**Comment by nalgeon** [comment]
I like `~/.sqlpkg`.
